### ISSUE TITLE
Module Import Error

### ISSUE THREAD

**Issue by surajpandey353** [tensorflow/model-optimization#1104]
Hi,
 
** Describe the Bug**
I am trying to use the latest tensorflow_model_optimization with tensorflow 2.14.0 and I am unable to import  the module.

**System information**
TensorFlow version : 2.14.0
TensorFlow Model Optimization : 0.7.5
Python version: 3.11

**Describe the current behavior**
`
>>> import tensorflow as tf
2023-12-18 16:56:23.753782: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-18 16:56:23.753816: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-18 16:56:23.753842: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-18 16:56:23.760081: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-18 16:56:24.486506: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> tf.__version__
'2.14.0'
>>> import keras
>>> keras.__version__
'3.0.0'
>>> import tensorflow_model_optimization as tfmot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/__init__.py", line 86, in <module>
    from tensorflow_model_optimization.python.core.api import clustering
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/api/__init__.py", line 16, in <module>
    from tensorflow_model_optimization.python.core.api import clustering
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py", line 16, in <module>
    from tensorflow_model_optimization.python.core.api.clustering import keras
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py", line 19, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_scope
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py", line 22, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras import cluster_wrapper
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py", line 23, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras import clustering_centroids
  File "/.local/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py", line 23, in <module>
    k = tf.keras.backend
        ^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/py311pt21/lib/python3.11/site-packages/tensorflow/python/util/lazy_loader.py", line 66, in __getattr__
    module = self._load()
             ^^^^^^^^^^^^
  File "/anaconda3/envs/py311pt21/lib/python3.11/site-packages/tensorflow/python/util/lazy_loader.py", line 49, in _load
    module = importlib.import_module(self.__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/py311pt21/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'keras.api'
`

**Comment by cdh4696** [comment]
Could you please try to upgrade your Keras version?

https://stackoverflow.com/questions/71406007/modulenotfounderror-no-module-named-keras-api-error

**Comment by surajpandey353** [comment]
The last comment worked
