### ISSUE TITLE
sparsity.prune_low_magnitude fails with mixed precision policy mixed_float16

### ISSUE THREAD

**Issue by dd1923** [tensorflow/model-optimization#409]
**Describe the bug**
When using `tf.keras.mixed_precision.experimental.Policy("mixed_float16", loss_scale="dynamic")` the `sparsity.prune_low_magnitude` in tensor type conversion with the error `Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor 'pruning_ops/Cast_2:0' shape=(3, 3, 1, 12) dtype=float16>`. Things work perfectly fine when precision is set to the default float32. Looks like some piece of code is not properly respecting the dtype.

**System information**

TensorFlow installed from (source or binary): pip3

TensorFlow version: 2.2.0

TensorFlow Model Optimization version:

Python version: 3.6

**Describe the expected behavior**

The prune_low_magnitude should work with layers using mixed_float16 policy.

**Describe the current behavior**

Throws error described above.

**Code to reproduce the issue**
See this [colab ](https://colab.research.google.com/drive/185jF7fuxgTflLRTaOUJuSfTPrrPPvzWl)link.

**Screenshots**

**Additional context**

**Comment by dd1923** [comment]
@alanchiao any insights on when will this be fixed?

**Comment by dd1923** [comment]
@alanchiao Is this a major change? From the stack trace it looked more like a minor bug where some piece of code is not properly respecting the dtype.

**Comment by teijeong** [comment]
Hi @dd1923 , sorry for really late response.

Just want to check if this still bugs you before picking up this again.

**Comment by Etienne-DUPUIS** [comment]
Hi, I can confirm that the issue still exist
```
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor 'prune_low_magnitude_conv1/Mul:0' shape=(7, 7, 3, 64) dtype=float16> 
```

**Comment by paulds8** [comment]
This is an issue for me as well. TF2.4.1 with 0.5 of tensorflow_model_optimization

```
Traceback (most recent call last):
  File "/databricks/python/lib/python3.8/site-packages/SCVS/app.py", line 40, in main
    task.start()
  File "/databricks/python/lib/python3.8/site-packages/SCVS/pipeline/task.py", line 223, in start
    self.run()
  File "/databricks/python/lib/python3.8/site-packages/SCVS/pipeline/train_object_detection.py", line 205, in run
    custom_train_loop(
  File "/databricks/python/lib/python3.8/site-packages/SCVS/ml/tf_training.py", line 295, in custom_train_loop
    detection_model._feature_extractor._efficientnet = tfmot.sparsity.keras.prune_low_magnitude(
  File "/databricks/python/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/prune.py", line 184, in prune_low_magnitude
    return keras.models.clone_model(
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 430, in clone_model
    return _clone_functional_model(
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 200, in _clone_functional_model
    functional.reconstruct_from_config(model_configs,
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1285, in reconstruct_from_config
    process_node(layer, node_data)
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1233, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /databricks/python/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py:258 call  *
        self.add_update(self.pruning_obj.weight_mask_op())
    /databricks/python/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py:195 weight_mask_op  *
        return tf.group(self._weight_assign_objs())
    /databricks/python/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py:190 _weight_assign_objs  *
        assign_objs.append(tf_compat.assign(weight, masked_weight))
    /databricks/python/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/keras/compat.py:28 assign  *
        return ref.assign(value, name=name)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/autocast_variable.py:236 assign  **
        return self._apply_assign_update(self._variable.assign, value, use_locking,
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/autocast_variable.py:209 _apply_assign_update
        assign_op = update_fn(value, use_locking, name, False)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/values.py:781 assign
        return values_util.on_write_assign(
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/values_util.py:140 on_write_assign
        return var._update(  # pylint: disable=protected-access
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/values.py:940 _update
        return self._update_cross_replica(update_fn, value, **kwargs)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/values.py:893 _update_cross_replica
        return self.distribute_strategy.extended.update(
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2494 update
        return self._update(var, fn, args, kwargs, group)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_strategy.py:710 _update
        fn(v, *distribute_utils.select_replica_mirrored(i, args),
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/distribute/values_util.py:139 <lambda>  **
        assign_fn = lambda var, *a, **kw: var.assign(*a, **kw)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py:882 assign
        value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /databricks/python/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1507 convert_to_tensor
        raise ValueError(

    ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor 'prune_low_magnitude_stem_conv2d/Mul:0' shape=(3, 3, 3, 48) dtype=float16>

```

**Comment by A-strategist** [comment]
I find the result layer from prune_low_magnitude would end up with different dtype_policy from the original one. And here is a solution: call _set_dtype_policy after prune_low_magnitude.

for example
```python
from tensorflow.keras import models, layers
import tensorflow_model_optimization as tfmo

d1 = layers.Dense(5, dtype='mixed_float16')
d2 = layers.Dense(5, dtype='mixed_float16')

print(d1.dtype_policy)
print(d2.dtype_policy)

d11 = tfmo.sparsity.keras.prune_low_magnitude(d1) 
d22 = tfmo.sparsity.keras.prune_low_magnitude(d2) 

print(d11.dtype_policy)
print(d22.dtype_policy)

d11._set_dtype_policy(d1.dtype_policy)
d22._set_dtype_policy(d2.dtype_policy)

print(d11.dtype_policy)
print(d22.dtype_policy)

# now it works fine
inp = layers.Input((10))
tensor = d11(inp)
tensor = d22(tensor)
m = models.Model(inputs=inp, outputs=tensor)
m.compile(loss='mse')
```

I haven't try global policy, but it should be the same
