### ISSUE TITLE
AttributeError: 'NoOpActivation' object has no attribute '__name__'

### ISSUE THREAD

**Issue by FredHuang16** [tensorflow/model-optimization#556]
Traceback (most recent call last):
  File "train_mobilenetv2_quantization.py", line 368, in <module>
    base_model = quantize_model(base_model)
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 138, in quantize_model
    return quantize_apply(annotated_model)
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 410, in quantize_apply
    unwrapped_model, layer_quantize_map)
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_layout_transform.py", line 73, in apply
    set(layer_quantize_map.keys()), layer_quantize_map).transform()
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/quantization/keras/graph_transformations/model_transformer.py", line 529, in transform
    copy.deepcopy(match_layer_node))
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_transforms.py", line 250, in replacement
    return self._replace(relu_layer_node, bn_layer_node, conv_layer_node)
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_transforms.py", line 239, in _replace
    keras.activations.serialize(quantize_aware_activation.NoOpActivation())
  File "/home/huangfei/anaconda3/envs/ImageSearch2/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 287, in serialize
    if activation.__name__ in _TF_ACTIVATIONS_V2:
AttributeError: 'NoOpActivation' object has no attribute '__name__'

**Comment by cuongdv1** [comment]
@FredHuang16,
Have you solved this issue?

**Comment by teijeong** [comment]
Hi @FredHuang16 , @cuongdv1 , can you provide steps to reproduce this issue?

**Comment by Bimde** [comment]
I got this same issue. Finally realized it was because I was using the toolkit with TF 1.14. Using TF 2.4.1 made this go away for me.
